### ISSUE TITLE
MASH-FRET bug report

### ISSUE THREAD

**Issue by pflanzenhueter** [RNA-FRETools/MASH-FRET#16] opened 2019-03-15 09:41 UTC
**Describe the bug**

**To Reproduce**

**Error Code**
Reference to non-existent element of a cell array.

Error in ud_kinPrm (line 22)
wght = p.kin_start{curr_k,1}(4)*p.kin_start{curr_k,1}(1);

Error in pushbutton_TDPupdateClust_Callback (line 87)
        prm = ud_kinPrm(prm,Jopt);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MASH (line 19)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)MASH('pushbutton_TDPupdateClust_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating UIControl Callback

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]
 - Matlab Version [e.g. 2016a]
 - MASH-FRET Version [1.1.2]

**Additional context**

**Your contact**
Leave your email address.

**Comment by mca-sh** [comment] 2019-03-18 18:24
Issue should be fixed; see commit [here](https://github.com/RNA-FRETools/MASH-FRET/commit/101cac1602d65602006dbf562b5e8cdd0d3eda23).

To apply changes to the corrupted MASH project, the bootstrapped Gaussian fit (or thresholding) must be repeated and project must be save.

**Comment by mca-sh** [comment] 2019-03-18 21:18
I can't reproduce the error.
Do you remember what led to the error?

**Comment by mca-sh** [comment] 2019-03-25 19:38
I could finally reproduce and manage the error (see commit [here](https://github.com/RNA-FRETools/MASH-FRET/commit/3ec3622980488fd7274b43c6d91ba103f00ba179)).

**Closed by mca-sh** 2019-03-25 19:38 UTC
Labels: bug
