### ISSUE TITLE
Use to take trajectories for just one channel?

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#130] opened 2024-03-13 00:36 UTC
Hey Melodie,

Is it possible to track the trajectories of just a single channel with one laser? When I try to transform or calculate, the program says the feature is only possible with 2 or more channels, so I am assuming it is not possible. However, I was wondering if it would be possible to implement this? If not, that is okay. 

Many Thanks,
Sydney Nguyen

**Comment by mca-sh** [comment] 2024-03-13 07:34
Hi Sydney,

MASH is adapted to the analysis of one-channel one-laser data. 
You don't need to transform coordinates since you have only one channel.
But I see where is the problem: spots coordinates are not automatically loaded for intensity calculation.

You will have to do it manually for now until I adapt the code, that is:
1. run Spotfinder
2. after you obtain a satisfying set of coordinates, press ![image](https://github.com/RNA-FRETools/MASH-FRET/assets/7199132/20f9a577-cb33-4517-9c04-eca2785ca1e8) and export them to a .spots file
3. In panel "Intensity integration", press `Import options` and check that `number of header lines` is 1, and the `x-col` and `y-col` are 1 and 2, respectively, to correspond to the structure of the .spot file
4. press ![image](https://github.com/RNA-FRETools/MASH-FRET/assets/7199132/3563e5ee-b175-4bf4-9bed-ee1df9ec6a31) and import your .spots file
5. You can now create your trajectories

Tell me if it works for you.
Best,
Mélodie

**Comment by snguyen49** [comment] 2024-03-13 15:01
Okay, I will try that!

Many Thanks,
Sydney
________________________________

**Comment by snguyen49** [comment] 2024-03-13 18:13
Hey Melodie,

I attempted to do as you said. Unfortunately, I am obtaining this error:

![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/219fecce-8f4c-4d1c-839e-2c75c2fd47e1)

Many Thanks,
Sydney

**Comment by mca-sh** [comment] 2024-03-14 07:20
Hi Syndney,

Mmm this is strange.
I could not reproduce the error by exporting and importing a .spots file.
May I ask the .spots file you used? May be the structure is different for some reasons..

Mélodie

**Comment by mca-sh** [comment] 2024-03-14 11:31
Hey Sydney,

Meanwhile I've been implemented automatic loading of spots coordinates for intensity calculation.
You don't need to export and import spots coordinates anymore, just run Spotfinder and calculate traces.
Can you try this version and give me your feedback please? https://github.com/RNA-FRETools/MASH-FRET/tree/auto-load-coord-1chan
Thanx,
Mélodie

**Comment by snguyen49** [comment] 2024-03-14 13:25
Hi Melodie,

Here is the .spots file.

Many Thanks,
Sydney
________________________________

**Comment by mca-sh** [comment] 2024-03-14 13:58
Hi Sydney,
the spots file has been erased by Github, can you please send it back to me on github (https://github.com/RNA-FRETools/MASH-FRET/issues/130)?
Thank you,
Mélodie

**Comment by snguyen49** [comment] 2024-03-14 14:38
> Hi Sydney, the spots file has been erased by Github, can you please send it back to me on github (#130)? Thank you, Mélodie

It is telling me that it does not support that file type. Do you mind if I email it to you directly?

Thank you,
Sydney

**Comment by mca-sh** [comment] 2024-03-14 14:40
I see. 
No of course I don't mind

**Comment by snguyen49** [comment] 2024-03-14 14:59
Also, the one channel MASH-FRET works. 🙂

Thank you,
Sydney
________________________________

**Comment by mca-sh** [comment] 2024-03-14 15:04
Thank you Sydney,
Well nothing looks different in the file, I don't really understand what happened..
As the one-channel is working, I will leave it for now and close this issue.
Mélodie

**Closed by mca-sh** 2024-03-14 15:04 UTC
Labels: question
