### ISSUE TITLE
BIC-ML-DPH is not running, Error :  Error while evaluating UIControl Callback, in the section of Kinetic model, in transition analysis 

### ISSUE THREAD

**Issue by gtripathi1** [RNA-FRETools/MASH-FRET#115] opened 2024-01-10 20:21 UTC
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/156243133/c447c88f-6a4e-4559-84e5-11b603be12d3)
BIC-ML-DPH is not running, Error : Error while evaluating UIControl Callback, 
in the section on Kinetic model, in transition analysis.
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/156243133/23e0c8d8-3847-46e9-8680-c171ddd61907)
These are the parameters.
Email: gtripathi1@student.gsu.edu

**Comment by mca-sh** [comment] 2024-01-11 09:15
Hello gtripathi1 and thank you for reporting thib bug.

Could you please copy/paste the entire error message (all red text) from the MATLAB command window?
What is the most interesting for me is the top-most error messages.

Best,
Mélodie

**Comment by gtripathi1** [comment] 2024-01-11 16:04
***@***.***
HI
I have attached the photo of the complete screen of command window which appears as I click on ML-DPH button.
Please have a look.

Regards
Gauri Tripathi

**Comment by mca-sh** [comment] 2024-01-11 18:03
Hi,
Sorry to insist, but  I am pretty sure a part of it is missing since the reason causing the error is not displayed.
And I need this information to know where the bug is coming from since I can't reproduce it.
Could you please scroll up the command window to get the full error, and copy/paste it here?
Thank you

**Comment by gtripathi1** [comment] 2024-01-12 17:42
***@***.******@***.******@***.******@***.******@***.***
Hi,
I have these errors occurring while I am calculating traces, so I am unable to calculate traces. Please have a look.
Regards
Gauri Tripathi

**Comment by gtripathi1** [comment] 2024-01-12 17:45
Hi,
I have a problem, whenever I click import options for input coordinates, and all the tabs get stucked after that, no tabs gets closed , once that tab is open. I am attaching the photo of the tab, please have a look. ***@***.***
Regards
Gauri Tripathi

**Comment by mca-sh** [comment] 2024-01-15 08:33
Hi Gauri Tripathi,

I see you have many bugs here.
However, I can't access the images you are attaching to your email since our exchanges are mediated by Github.
You need to post your images via Github, where you posted originally your issue (here: https://github.com/RNA-FRETools/MASH-FRET/issues/115).

Also please, Can you copy/paste all the red **text** from the command window (scroll up!) instead of screenshots? This would help me to solve your issues.

Best,
Mélodie

**Comment by mca-sh** [comment] 2024-05-29 06:16
Hello,
In absence of response, I close this issue now.
Do not hesitate to open a new one if you encounter another bug.
Best,
Mélodie

**Closed by mca-sh** 2024-05-29 06:16 UTC
Labels: bug
