### ISSUE TITLE
Rotation of average image in trace manager

### ISSUE THREAD

**Issue by Kevinkraft7** [RNA-FRETools/MASH-FRET#52] opened 2019-11-25 15:12 UTC
**Description of the Bug**

When you have a movie loaded in video processing of the MASH-FRET software and want to analyze the mash file generated of this movie, it filps the average 180° and then turns it 90° clockwise (compare screenshots below and look at the bright dots and their respective location)  
So now the molecules are compared in the same channel instead of betwen the two different channels. Meaning a molecule is matched with another molecule also from the green channel instead of the signal from the same molecule in the red channel.
When you close and re-open MASH-FRET and just load the MASH-file (the same one that didnt work before) its fine, given that no movie is loaded into the video processing part.

**To reproduce**
Make the normal video processing procedure and when your done, load the mash file into traces processing (do all the adjustments like factor corrections and so or not (doesnt matter for the issue)) and open the trace manager. go to View on Video and you will see that the picture is flipped and rotated.

**Error code:**
No error code appears at any step of the bug.

**Expected behavior:**
That the average image will not change its orientation.

**Screenshots:**
![Screenshot 2019-11-25 00 25 36](https://user-images.githubusercontent.com/48956713/69531494-4109b680-0f74-11ea-9d4f-1a2fef594578.jpg)
![Screenshot 2019-11-25 00 24 16](https://user-images.githubusercontent.com/48956713/69531506-46670100-0f74-11ea-81de-709349022e09.png)

**Desktop:**

OS Windows 10 (also checked with 8.1)
Matlab Version 2017a
MASH-FRET version 1.1.2 (prev. commit 6bc4127)

**Contact:**
Kevin Kraft
k.kraft@bioc.uzh.ch

**Comment by mca-sh** [comment] 2019-11-28 14:09
Hi Kevinkraft7,

Thank you for the bug report.
Unfortunately I can't reproduce the dysfunction.
Could you give me more details about it:
- is it reproducible?
- if it is reproducible, does it happen with other projects?
- if it happens with only one project, could you attach the corresponding .mash file to your request?

**Comment by Kevinkraft7** [comment] 2019-12-19 18:12
Hi mca-sh,

Yes it is reproducible with all Mash files. The problem is not the Mash-file itself but when the respective movie (sira or sif file) is loaded in in the movie processing part and you then want to proceed with traces processing . You can load the same Mash file into Mash-fret without the movie loaded in traces processing and you do not see the bug.

**Comment by mca-sh** [comment] 2020-01-10 12:16
Ok, thank you for the details.
I still can't reproduce it, even with problematic data sets.
However, I've corrected something that might be the source of the problem.

Can you try to reproduce the bug using [this version](https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-12.zip) of MASH?

**Comment by Kevinkraft7** [comment] 2020-01-10 12:24
Sure I will try it again in a few hours.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: mca-sh <notifications@github.com> Datum: 10.01.20  13:16  (GMT+01:00) An: RNA-FRETools/MASH-FRET <MASH-FRET@noreply.github.com> Cc: Kevinkraft7 <kevin.kraft@uzh.ch>, Author <author@noreply.github.com> Betreff: Re: [RNA-FRETools/MASH-FRET] Rotation of average image in trace manager (#52) Ok, thank you for the details.
I still can't reproduce it, even with problematic data sets.
However, I've corrected something that might be the source of the problem.
Can you try to reproduce the bug using this version of MASH?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RNA-FRETools/MASH-FRET/issues/52?email_source=notifications\u0026email_token=ALVQKKOILA6AY2HDWCFV36LQ5BRJDA5CNFSM4JRKMO22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEITXYHI#issuecomment-573013021",
"url": "https://github.com/RNA-FRETools/MASH-FRET/issues/52?email_source=notifications\u0026email_token=ALVQKKOILA6AY2HDWCFV36LQ5BRJDA5CNFSM4JRKMO22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEITXYHI#issuecomment-573013021",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Kevinkraft7** [comment] 2020-01-11 14:32
Tried again with the new MASH and didnt have the problem anymore
Tried two different files so I think it si indeed fixed-

Best,
Kevin

-----"mca-sh" <notifications@github.com> schrieb: -----
An: "RNA-FRETools/MASH-FRET" <MASH-FRET@noreply.github.com>
Von: "mca-sh" <notifications@github.com>
Datum: 10.01.2020 13:16
Kopie: "Kevinkraft7" <kevin.kraft@uzh.ch>, "Author" <author@noreply.github.com>
Betreff: Re: [RNA-FRETools/MASH-FRET] Rotation of average image in trace manager (#52)

Ok, thank you for the details.
 I still can't reproduce it, even with problematic data sets.
 However, I've corrected something that might be the source of the problem.
 Can you try to reproduce the bug using this version of MASH?

**Comment by mca-sh** [comment] 2020-01-11 20:00
Great!
Thank you for the test.
I close the issue.

**Closed** 2020-01-11 20:00 UTC
Labels: bug
