### ISSUE TITLE
Merging traces with Dynamic Background

### ISSUE THREAD

**Issue by nsivan16** [RNA-FRETools/MASH-FRET#136] opened 2024-07-17 14:17 UTC
**Describe the bug**
Once traces are merged with a dynamic background, they are no longer corrected for the dynamic background.

**To Reproduce**
1. Have different data sets corrected for dynamic background
2. Merge
3. See error

**Error Code**
-

**Expected behavior**
Merging the traces with the corrected dynamic background

**Screenshots**
Traces prior to merge --> with dynamic background correction
![image](https://github.com/user-attachments/assets/4961c029-9d8f-4199-a49a-25536789d4dc)

Same trace after merging
![image](https://github.com/user-attachments/assets/89db91d6-8c40-47f7-8117-3848e14f8460)

**Project file(s)**
If applicable, send the `.mash` files concerned by the bug to melodiehadzic@protonmail.com.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Matlab Version: 2022b
 - MASH-FRET Version [1.3.4 (prev. commit: 5682247f)]

**Comment by mca-sh** [comment] 2024-07-21 16:31
Hi Nirusan and thank you for the bug report and the .mash files.

Indeed, dynamic background correction was not retained after the merging process since the method is automatically reset to "Manual", where a single value is subtracted to the trajectory.

I tried to handle the bug by locking the background correction prior merging projects. This means that background is corrected before merging and can not be modified after merging (you will see, the edit fields are off-enabled).
You can find the updated version here: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/master.zip

Please tell me is it works for you (I could not do it myself on your .mash files since I needed the associated video files as well).

Best,
Mélodie

**Comment by nsivan16** [comment] 2024-07-24 14:59
Hi Mélodie,

Sorry for the delayed response. I’ve tested the new version. However, it only locks the background for the first channel (see green in pdf file) and not for all the traces. Therefore I’ve attached a file with some screenshot to show you the difference between the single and the merged files.

Best,
Niru

**Comment by mca-sh** [comment] 2024-07-26 10:24
Hi Nirusan,

Thank you for the feedback.
Unfortunately the attached files are not transmitted when the email exchange is mediated by Github.
Can you either send me the files via the issue tracker of GitHub ([#136](https://github.com/RNA-FRETools/MASH-FRET/issues/136)) or via a brand new email to my address (melodiehadzic@protonmail.com)?

In any case, I was not able to reproduce the error with my own files.
So for the moment I can only recommend to check that the dynamic background correction was applied to each of the trajectories and that intensity calculations were updated (press `UPDATE ALL`) prior merging.

Thank you,
Mélodie

**Comment by mca-sh** [comment] 2024-08-06 08:15
Hey Nirusan,

Thank you very much for all the files.
I don't understand because from my side, dynamic background correction is preserved after merging the two files `eSce_03_processed.mash` and `eSce_04_processed.mash`.

Be sure to use the last version of MASH ([here](https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/master.zip)) and delete all older version from your computer, just in case.

This is the exact procedure I followed:
1. open `eSce_03_processed.mash` and select the corresponding `frame_t_0.ets` file when requested
2. in panel "Background correction" of module "Trace Processing", check that the checkboxes `dynamic` and `apply` are activated for each trace in the popup menu `data`
3. press `all` in panel "Background correction" and then `Apply` in the popup window
4. press `UPDATE ALL` to re-calculate all intensities
5. repeat steps 1-4 with file `eSce_04_processed.mash`
6. merge the two projects

I guess you followed a similar procedure, but something might be different since we do not obtain the same results!
Can you do the exact same steps and tell me if it is working/not?

Thanx,
Mélodie

**Comment by mca-sh** [comment] 2024-08-06 08:20
You can find the successfully merged project here: [merged_eSce_03_and_04_MH.zip](https://github.com/user-attachments/files/16507468/merged_eSce_03_and_04_MH.zip)
Can you also try to open it in MASH and see if the background panel is correctly locked?

**Comment by nsivan16** [comment] 2024-08-06 10:41
Hi Mélodie,

I have deleted and downloaded the newest version of MASH. That helped. Thank you!

Best,
Niru

**Closed** 2024-08-06 10:43 UTC
Labels: bug
