### ISSUE TITLE
FRET Traces not showing up in Trace processing 

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#132] opened 2024-04-29 06:27 UTC
Hey Melodie,

I am running the most recent version of MASH-FRET and noticed that sometimes the FRET Traces were not being calculated. I was wondering if that was on purpose and if I have to press something to have it show up.

![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/417cc488-efc3-4144-8033-95b73b284e46)

Here is an image of the issue.

Best,
Sydney

**Comment by snguyen49** [comment] 2024-04-29 06:50
Hey Melodie,

It seems that when I denote channel 1 as donor and channel 2 as acceptor at the beginning when importing the video it works. I am not really sure why but that is good enough for me.

Many Thanks,
Sydney

**Comment by mca-sh** [comment] 2024-04-29 06:57
Hi Sydney,

Thank you for reporting this bug.
I guess you set the number of channels to two in the experiment settings.
Did you check the "FRET calculations" tab to see if the FRET pair donor/acceptor is still declared?
If yes, how were the channels named when you had this bug?
Normally, FRET calculations should not depend on the channel names..

Best,
Mélodie

**Comment by snguyen49** [comment] 2024-04-29 07:06
Oh oop. You were right. I must have missed it the first time around. Thank you!

Best,
Sydney

**Comment by mca-sh** [comment] 2024-04-29 07:11
If this was not the cause and you ever encounter this bug again, despite the FRET calculations being well-defined, please repost an issue, I will close this one for now.
Mélodie

**Closed by mca-sh** 2024-04-29 07:11 UTC
Labels: bug

**Comment by snguyen49** [comment] 2024-04-29 15:19
okay thank you!

________________________________
